# -*- coding: utf-8 -*-
"""3104_T16_HOIHUB

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H4VoYPIxYRFWWCT-bRP1HQrgjCDLte9g
"""



"""# HOIHUB T16
Welcome!
"""

print("Hello from Binder!")

"""## Imports and Setup

Let's start with the base imports.
"""

# This Colab requires TF 2.5.
!pip install -U "tensorflow>=2.5"

import os
import pathlib

import matplotlib
import matplotlib.pyplot as plt

import io
import scipy.misc
import numpy as np
from six import BytesIO
from PIL import Image, ImageDraw, ImageFont
from six.moves.urllib.request import urlopen

import tensorflow as tf
import tensorflow_hub as hub

tf.get_logger().setLevel('ERROR')

"""## Data Exploration

-Description

## Inference

-Description

## Training

-Desc

## Testing

-Desc
"""